<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Identity\SlackApp.Modules.Identity.csproj" />
    <ProjectReference Include="..\Messaging\SlackApp.Modules.Messaging.csproj" />
    <ProjectReference Include="..\Presence\SlackApp.Modules.Presence.csproj" />
  </ItemGroup>

</Project>
